import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { AUTOJUNK_MIN_LENGTH, autojunkedCharacters, matchingBlocks, sequenceRatio } from './seq-ratio.js';

/**
 * The G2 acceptance bar (admin/SPEC.md section 5). `__fixtures__/seq-ratio-parity.json` was
 * generated by running CPython's own `difflib.SequenceMatcher(None, a, b).ratio()` over the real
 * bank, so this compares against the function being ported rather than against hand-written
 * expectations. Regenerate it with the snippet recorded in the fixture's `note` if the bank grows.
 */
interface ParityFixture {
  readonly note: string;
  readonly generated: string;
  readonly python_version: string;
  readonly autojunk_candidates: readonly string[];
  /** Deduplicated operands. The same 293 candidates recur across every pair. */
  readonly strings: readonly string[];
  /** `[aIndex, bIndex, ratio]`. Indexed rather than inlined — inlining the strings made the file 4.6 MB. */
  readonly pairs: readonly [number, number, number][];
}

const HERE = dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(
  readFileSync(join(HERE, '__fixtures__', 'seq-ratio-parity.json'), 'utf8'),
) as ParityFixture;

function operands(pair: readonly [number, number, number]): { a: string; b: string } {
  const a = fixture.strings[pair[0]];
  const b = fixture.strings[pair[1]];
  if (a === undefined || b === undefined) {
    throw new Error(`fixture index out of range: ${String(pair[0])}, ${String(pair[1])}`);
  }
  return { a, b };
}

describe('sequenceRatio — CPython difflib parity', () => {
  it('loaded a fixture large enough to be meaningful', () => {
    expect(fixture.pairs.length).toBeGreaterThan(28_000);
    expect(fixture.autojunk_candidates).toHaveLength(3);
  });

  it('reproduces every recorded ratio exactly', () => {
    const mismatches: { a: string; b: string; want: number; got: number }[] = [];
    for (const pair of fixture.pairs) {
      const { a, b } = operands(pair);
      const got = sequenceRatio(a, b);
      // Exact equality, not a tolerance. Both sides compute 2*M/T in IEEE-754 doubles from the same
      // integer M and T, so any difference means the block search diverged, not that a float drifted.
      if (got !== pair[2]) {
        mismatches.push({ a, b, want: pair[2], got });
      }
    }
    expect(mismatches.slice(0, 5)).toEqual([]);
    expect(mismatches).toHaveLength(0);
  });
});

describe('autojunk', () => {
  it('does not fire below the threshold', () => {
    expect(autojunkedCharacters('a'.repeat(AUTOJUNK_MIN_LENGTH - 1)).size).toBe(0);
  });

  it('fires at the threshold', () => {
    // 200 chars, all 'a': ntest = 200/100 + 1 = 3, and 200 > 3, so 'a' is dropped.
    expect([...autojunkedCharacters('a'.repeat(AUTOJUNK_MIN_LENGTH))]).toEqual(['a']);
  });

  it('fires on all three real bank candidates that cross the threshold', () => {
    for (const candidate of fixture.autojunk_candidates) {
      expect(candidate.length).toBeGreaterThanOrEqual(AUTOJUNK_MIN_LENGTH);
      expect(autojunkedCharacters(candidate).size).toBeGreaterThan(0);
    }
  });

  it('leaves a rare character indexed while dropping a common one', () => {
    // 'q' appears once; ' ' and 'a' appear far more than ntest.
    const b = `${'a '.repeat(120)}q`;
    const dropped = autojunkedCharacters(b);
    expect(dropped.has('a')).toBe(true);
    expect(dropped.has(' ')).toBe(true);
    expect(dropped.has('q')).toBe(false);
  });

  it('makes the function asymmetric on a real pair', () => {
    // Trap 2: autojunk is computed over `b` only, so argument order changes the score. If this ever
    // starts passing as symmetric, the heuristic has stopped being applied.
    const long = fixture.autojunk_candidates[0];
    const short = 'describe program';
    expect(long).toBeDefined();
    expect(sequenceRatio(short, long as string)).not.toBe(sequenceRatio(long as string, short));
  });

  it('absorbs an autojunked character into a match rather than treating it as junk', () => {
    // Trap 3: ' ' is dropped from the index here, but the extension loops must still cross it, so
    // the two strings score as fully identical.
    const b = `${'ab '.repeat(80)}z`;
    expect(autojunkedCharacters(b).has(' ')).toBe(true);
    expect(sequenceRatio(b, b)).toBe(1);
  });
});

describe('degenerate inputs', () => {
  it('scores two empty strings as 1', () => {
    expect(sequenceRatio('', '')).toBe(1);
  });

  it('scores an empty string against a non-empty one as 0', () => {
    expect(sequenceRatio('', 'abc')).toBe(0);
    expect(sequenceRatio('abc', '')).toBe(0);
  });

  it('scores a string against itself as 1', () => {
    expect(sequenceRatio('the quick brown fox', 'the quick brown fox')).toBe(1);
  });

  it('is 2*M/T, not an edit-distance ratio', () => {
    // 'abcdef' vs 'fedcba' shares only single characters; the longest block search finds one of
    // size 1, giving 2*1/12.
    expect(sequenceRatio('abcdef', 'fedcba')).toBeCloseTo(2 / 12, 12);
  });
});

describe('matchingBlocks', () => {
  it('finds the single longest common run', () => {
    const blocks = matchingBlocks('xxabcdyy', 'zzabcdzz');
    const total = blocks.reduce((n, b) => n + b.size, 0);
    expect(total).toBe(4);
    expect(blocks.some((b) => b.size === 4 && b.aStart === 2 && b.bStart === 2)).toBe(true);
  });

  it('recurses into both sides of a match', () => {
    // 'a' before the shared 'MID', 'z' after it — both must be found by the recursion.
    const blocks = matchingBlocks('aMIDz', 'aMIDz');
    expect(blocks.reduce((n, b) => n + b.size, 0)).toBe(5);
  });

  it('returns nothing for disjoint inputs', () => {
    expect(matchingBlocks('abc', 'xyz')).toEqual([]);
  });
});
