import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { loadBank } from './data.js';
import { normalize } from './matcher.js';
import { AUTOJUNK_MIN_LENGTH, autojunkedCharacters, matchingBlocks, sequenceRatio } from './seq-ratio.js';

/**
 * The G2 acceptance bar (admin/SPEC.md section 5). `__fixtures__/seq-ratio-parity.json` was
 * generated by running CPython's own `difflib.SequenceMatcher(None, a, b).ratio()` over the real
 * bank, so this compares against the function being ported rather than against hand-written
 * expectations. Regenerate it with `scripts/regenerate-seq-ratio-parity.py` when the bank changes.
 *
 * A parity fixture is only worth its coverage of the bank it is checked in beside, and coverage is
 * exactly what goes stale silently: the v0.4.0 bank edit added 35 candidate strings and six that
 * cross the autojunk threshold, and the fixture generated against the 82/211 bank still passed a
 * `pairs.length > 28_000` assertion while three of those six had never been compared against
 * CPython. The coverage assertions below are derived from the live bank for that reason — never
 * hard-code a count that a stale fixture can satisfy.
 */
interface ParityFixture {
  readonly note: string;
  readonly generated: string;
  readonly python_version: string;
  /** Every candidate at or over {@link AUTOJUNK_MIN_LENGTH}, as the generator found them. */
  readonly autojunk_candidates: readonly string[];
  /** Deduplicated operands; the same candidates recur as `b` across every pair. */
  readonly strings: readonly string[];
  /** `[aIndex, bIndex, ratio]`. Indexed rather than inlined — inlining the strings made the file 4.6 MB. */
  readonly pairs: readonly [number, number, number][];
}

const HERE = dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(
  readFileSync(join(HERE, '__fixtures__', 'seq-ratio-parity.json'), 'utf8'),
) as ParityFixture;

function operands(pair: readonly [number, number, number]): { a: string; b: string } {
  const a = fixture.strings[pair[0]];
  const b = fixture.strings[pair[1]];
  if (a === undefined || b === undefined) {
    throw new Error(`fixture index out of range: ${String(pair[0])}, ${String(pair[1])}`);
  }
  return { a, b };
}

/** Every string `matcher.score()` can pass as `b`, normalized exactly as it would be at match time. */
function candidateStrings(): string[] {
  const out: string[] = [];
  for (const q of loadBank().questions) {
    out.push(normalize(q.canonical).join(' '));
    for (const v of q.variants) out.push(normalize(v.text).join(' '));
  }
  return [...new Set(out)].filter((s) => s !== '');
}

const bSideStrings = new Set(
  fixture.pairs.map((p) => fixture.strings[p[1]]).filter((s): s is string => s !== undefined),
);

describe('sequenceRatio — CPython difflib parity', () => {
  it('loaded a fixture large enough to be meaningful', () => {
    expect(fixture.pairs.length).toBeGreaterThan(28_000);
  });

  // The gate that a hard-coded count cannot provide: if the bank gains a candidate and the fixture
  // is not regenerated, that candidate has never been compared against CPython, and every other
  // assertion here still passes. Fix by running scripts/regenerate-seq-ratio-parity.py.
  it('compares every candidate in the current bank against CPython as `b`', () => {
    const uncovered = candidateStrings().filter((c) => !bSideStrings.has(c));
    expect(uncovered.map((c) => `${c.slice(0, 60)}… (${String(c.length)} chars)`)).toEqual([]);
  });

  it('reproduces every recorded ratio exactly', () => {
    const mismatches: { a: string; b: string; want: number; got: number }[] = [];
    for (const pair of fixture.pairs) {
      const { a, b } = operands(pair);
      const got = sequenceRatio(a, b);
      // Exact equality, not a tolerance. Both sides compute 2*M/T in IEEE-754 doubles from the same
      // integer M and T, so any difference means the block search diverged, not that a float drifted.
      if (got !== pair[2]) {
        mismatches.push({ a, b, want: pair[2], got });
      }
    }
    expect(mismatches.slice(0, 5)).toEqual([]);
    expect(mismatches).toHaveLength(0);
  });
});

describe('autojunk', () => {
  it('does not fire below the threshold', () => {
    expect(autojunkedCharacters('a'.repeat(AUTOJUNK_MIN_LENGTH - 1)).size).toBe(0);
  });

  it('fires at the threshold', () => {
    // 200 chars, all 'a': ntest = 200/100 + 1 = 3, and 200 > 3, so 'a' is dropped.
    expect([...autojunkedCharacters('a'.repeat(AUTOJUNK_MIN_LENGTH))]).toEqual(['a']);
  });

  // Derived from the bank, not counted: these are the strings where argument order changes the
  // score, so a new one that never reaches CPython is the most consequential gap the fixture can
  // have. The v0.4.0 bank took this from three candidates to six.
  it('records every bank candidate that crosses the threshold, and fires on each', () => {
    const crossing = candidateStrings().filter((c) => c.length >= AUTOJUNK_MIN_LENGTH);
    expect(crossing.length).toBeGreaterThan(0);
    expect([...fixture.autojunk_candidates].sort()).toEqual([...crossing].sort());

    for (const candidate of fixture.autojunk_candidates) {
      expect(candidate.length).toBeGreaterThanOrEqual(AUTOJUNK_MIN_LENGTH);
      expect(autojunkedCharacters(candidate).size).toBeGreaterThan(0);
      // Recorded is not the same as compared — the stale fixture listed candidates that appeared in
      // no pair at all.
      expect(bSideStrings.has(candidate)).toBe(true);
    }
  });

  it('leaves a rare character indexed while dropping a common one', () => {
    // 'q' appears once; ' ' and 'a' appear far more than ntest.
    const b = `${'a '.repeat(120)}q`;
    const dropped = autojunkedCharacters(b);
    expect(dropped.has('a')).toBe(true);
    expect(dropped.has(' ')).toBe(true);
    expect(dropped.has('q')).toBe(false);
  });

  it('makes the function asymmetric on a real pair', () => {
    // Trap 2: autojunk is computed over `b` only, so argument order changes the score. If this ever
    // starts passing as symmetric, the heuristic has stopped being applied.
    const long = fixture.autojunk_candidates[0];
    const short = 'describe program';
    expect(long).toBeDefined();
    expect(sequenceRatio(short, long as string)).not.toBe(sequenceRatio(long as string, short));
  });

  it('absorbs an autojunked character into a match rather than treating it as junk', () => {
    // Trap 3: ' ' is dropped from the index here, but the extension loops must still cross it, so
    // the two strings score as fully identical.
    const b = `${'ab '.repeat(80)}z`;
    expect(autojunkedCharacters(b).has(' ')).toBe(true);
    expect(sequenceRatio(b, b)).toBe(1);
  });
});

describe('degenerate inputs', () => {
  it('scores two empty strings as 1', () => {
    expect(sequenceRatio('', '')).toBe(1);
  });

  it('scores an empty string against a non-empty one as 0', () => {
    expect(sequenceRatio('', 'abc')).toBe(0);
    expect(sequenceRatio('abc', '')).toBe(0);
  });

  it('scores a string against itself as 1', () => {
    expect(sequenceRatio('the quick brown fox', 'the quick brown fox')).toBe(1);
  });

  it('is 2*M/T, not an edit-distance ratio', () => {
    // 'abcdef' vs 'fedcba' shares only single characters; the longest block search finds one of
    // size 1, giving 2*1/12.
    expect(sequenceRatio('abcdef', 'fedcba')).toBeCloseTo(2 / 12, 12);
  });
});

describe('matchingBlocks', () => {
  it('finds the single longest common run', () => {
    const blocks = matchingBlocks('xxabcdyy', 'zzabcdzz');
    const total = blocks.reduce((n, b) => n + b.size, 0);
    expect(total).toBe(4);
    expect(blocks.some((b) => b.size === 4 && b.aStart === 2 && b.bStart === 2)).toBe(true);
  });

  it('recurses into both sides of a match', () => {
    // 'a' before the shared 'MID', 'z' after it — both must be found by the recursion.
    const blocks = matchingBlocks('aMIDz', 'aMIDz');
    expect(blocks.reduce((n, b) => n + b.size, 0)).toBe(5);
  });

  it('returns nothing for disjoint inputs', () => {
    expect(matchingBlocks('abc', 'xyz')).toEqual([]);
  });
});
